# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('data', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('layout', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=500)),
                ('date_created', models.DateField()),
                ('finished', models.BooleanField(default=False)),
                ('assessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Assessee')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Forms')),
            ],
        ),
        migrations.CreateModel(
            name='MultiLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('data', models.CharField(max_length=10000)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Forms')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('data', models.BooleanField(default=False)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.MCQ')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('date_created', models.DateField(primary_key=True, serialize=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('data', models.CharField(max_length=500)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Forms')),
            ],
        ),
        migrations.AddField(
            model_name='forms',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Survey'),
        ),
        migrations.AddField(
            model_name='forms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackUser'),
        ),
        migrations.AddField(
            model_name='checkbox',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Forms'),
        ),
    ]
