# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='feedbackuser',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feedback.UserGroup'),
            preserve_default=False,
        ),
    ]
